# Generated by Django 4.1.7 on 2023-03-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterControlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_control_form', models.CharField(max_length=100, verbose_name='Форма семестрового контролю')),
            ],
            options={
                'verbose_name': 'Форма семестрового контролю',
                'verbose_name_plural': 'Форми семестрового контролю',
            },
        ),
        migrations.AlterModelOptions(
            name='groupstudent',
            options={'verbose_name': 'Групи-Студенти', 'verbose_name_plural': 'Групи-Студенти'},
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний профіль'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='semester_control_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.semestercontrolform', verbose_name='Форма семестрового контролю'),
        ),
    ]
