# Generated by Django 4.1.7 on 2023-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_semestercontrolform_alter_groupstudent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='semester',
            field=models.PositiveSmallIntegerField(verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_hours',
            field=models.PositiveSmallIntegerField(verbose_name='Загальна кількість годин'),
        ),
        migrations.AlterField(
            model_name='semestercontrolform',
            name='semester_control_form',
            field=models.CharField(max_length=50, verbose_name='Форма семестрового контролю'),
        ),
    ]
