# Generated by Django 4.1.7 on 2024-11-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дівоче прізвище'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дівоче прізвище'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='По батькові'),
        ),
    ]
